### ISSUE TITLE
send an email when the slide deck is created

### ISSUE THREAD

**Issue by davidwhogg** [astrodatagroup/slack-bot#2]
On Friday mornings, send an email to the relevant email list with the slide deck url.

Might be part of a more general functionality for the slack-bot. It may transcend slack. It may transcend its current cognitive limitations.

**Comment by megbedell** [comment]
> It may transcend its current cognitive limitations.

@davidwhogg are you trying to build skynet again

**Comment by davidwhogg** [comment]
I like the sign-off by the robot; it cheers me every week.
