### ISSUE TITLE
Add zoom link to message?

### ISSUE THREAD

**Issue by adrn** [astrodatagroup/slack-bot#4]
The only reason I didn't do this via PR is that I think the full link with password should be added as an env var to prevent zoom bombing (i.e., not checking in the password to this repo?). But maybe we aren't afraid, in which case it's a simple fix :)

**Comment by dfm** [comment]
I believe that this is now implemented.

**Comment by dfm** [comment]
I am confident that it works :)

**Comment by adrn** [comment]
❤️
